In [1]:
import numpy as np 

In [3]:
np.__version__

'1.18.5'

In [50]:
k ,m = int(input()),int(input())    #берем у пользователя K и  m  
np_array=np.arange(1,k*m+1).reshape(k,m)     #с помошью библиотеки numpy создаем нашу матрицу arange(start,end,step) . reshape() определяет размер матрицы 
np_array

10
10


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [41]:
rgn = np.random.default_rng(0)
np_array1 = rgn.integers(15 ,size=(3,5))
print(np_array1)                          #печатем изначальную матрицу для наглядности 
np.rot90(np_array1,3)                     #поворачиваем матрицу на 90 градусов в данном использовании np.rot90 принимает 2 парамтра матрицу и ось по которой будем поворацивать 

[[12  9  7  4  4]
 [ 0  1  0  2 12]
 [ 9 13  7  9 14]]


array([[ 9,  0, 12],
       [13,  1,  9],
       [ 7,  0,  7],
       [ 9,  2,  4],
       [14, 12,  4]], dtype=int64)

In [51]:
print(np_array)
for i in range(k):
    if i%2!=0:
        np_array[i] = np.flip(np_array[i])
np_array

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [100,  99,  98,  97,  96,  95,  94,  93,  92,  91]])

In [52]:
k ,m = int(input()),int(input())   
np_array=np.arange(1,k*m+1).reshape(k,m)     
np_array

3
5


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [236]:
arr=np.zeros(15).reshape(3,5)
arr1=[]
val =1

for i in range(len(np.ravel(arr))):
    row =0
    
    for j in range(len(np.ravel(arr))):
        if row<0 or i<0:
            continue
        if row<len(arr) and i<len(arr[row]):
            arr[row,i]=val
            val+=1
            arr1.append(arr[row,i])
        row+=1
        i-=1
    
print(arr1)
(arr)

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0]


array([[ 1.,  2.,  4.,  7., 10.],
       [ 3.,  5.,  8., 11., 13.],
       [ 6.,  9., 12., 14., 15.]])